###spring.datasource.url=jdbc:postgresql://localhost:5432/green_circle
#spring.datasource.username=postgres
#spring.datasource.password=1211

# CORS Configuration
#app.frontend.url=http://localhost:5173

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Neon PostgreSQL Database

spring.datasource.url=jdbc:postgresql://ep-square-base-az7sbi9z-pooler.c-3.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_oVwubgxL71YZ

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect